# Generated by Django 2.2.2 on 2019-06-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddr', models.CharField(max_length=62)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phoneNo', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('profilePic', models.ImageField(upload_to='')),
                ('dob', models.DateField()),
                ('company_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cmpaddr', to='Myapp.Address')),
                ('perma_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addr', to='Myapp.Address')),
            ],
        ),
    ]
