# Generated by Django 2.2.2 on 2019-06-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='Myapp.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='genderField',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='male', max_length=20),
        ),
    ]
